# Generated by nginx-cert -- shared HTTP entry point for every authority.
#
# A single validation mechanism, webroot-based. Version 1 proxied the challenge
# to a standalone certbot on a high port, which made renewal depend on an
# internal proxy and returned 502 permanently outside the renewal window. Here
# nginx serves the files the ACME client drops into %%WEBROOT%% directly:
# nothing to start, nothing to proxy.

server {
    listen      %%HTTP_PORT%%%%DEFAULT_SUFFIX%%;
    listen      [::]:%%HTTP_PORT%%%%DEFAULT_SUFFIX%%;
    server_name _;

    # -- HTTP-01 challenge: Let's Encrypt, ZeroSSL, Actalis, Buypass, Google --
    location ^~ /.well-known/acme-challenge/ {
        root         %%WEBROOT%%;
        default_type "text/plain";
        try_files    $uri =404;
        access_log   off;
    }

    # -- File validation for the ZeroSSL REST API (IP-address certificates) --
    # "root", not "alias": with alias, nginx stripped the location prefix from
    # the URI and looked one directory too high (systematic 404).
    location ^~ /.well-known/pki-validation/ {
        root         %%WEBROOT%%;
        default_type "text/plain";
        try_files    $uri =404;
        access_log   off;
    }

    # Plaintext liveness probe: usable by a load balancer or an orchestrator
    # without having to present a certificate.
    location = /healthz {
        access_log off;
        default_type text/plain;
        return 200 "ok\n";
    }

%%IF HTTP_REDIRECT%%
    location / {
        # 308 rather than 301: preserves the request method and body.
        return 308 %%REDIRECT_TARGET%%;
    }
%%ELSE%%
    location / {
        root  /var/www/html;
        index index.html;
    }
%%ENDIF%%
}
