# Generated by nginx-cert -- do not edit, changes are overwritten.
#
# http-level directives the generated servers depend on. They live in a snippet
# rather than inline in nginx.conf so that CERT_MANAGE_NGINX=false still works:
# with your own nginx.conf, the generated server blocks referenced
# $connection_upgrade and nginx refused to start with
# 'unknown connection_upgrade variable'.

# Transparent relaying of WebSocket connections to upstreams.
map $http_upgrade $connection_upgrade {
    default upgrade;
    ""      close;
}

# Where a plain-HTTP request for each host should be redirected, empty for the
# hosts that opted out with "redirect=false". The per-certificate option used
# to be parsed, stored, and then read by nothing at all.
map $host $nc_redirect_target {
    default   "%%DEFAULT_TARGET%%";
%%NO_REDIRECT_HOSTS%%
}
