# Generated by nginx-cert -- do not edit, changes are overwritten.
#
# http-level directives the generated servers depend on. They live in a snippet
# rather than inline in nginx.conf so that CERT_MANAGE_NGINX=false still works:
# with your own nginx.conf, the generated server blocks referenced
# $connection_upgrade and nginx refused to start with
# 'unknown connection_upgrade variable'.

# Transparent relaying of WebSocket connections to upstreams.
map $http_upgrade $connection_upgrade {
    default upgrade;
    ""      close;
}

# Where a plain-HTTP request for each host should be redirected, empty for a
# host that must be served over plain HTTP. The default is CERT_HTTP_REDIRECT;
# the lines under it are the certificates whose "redirect=" disagrees with it,
# in either direction.
map $host $nc_redirect_target {
    # Without "hostnames" a map key is matched literally, so the "*.example.com"
    # of a wildcard certificate matched a Host header spelled exactly that way
    # and nothing else: redirect= silently did nothing for every wildcard.
    hostnames;
    default   "%%DEFAULT_TARGET%%";
%%REDIRECT_OVERRIDES%%
}
