# +------------------------------------------------------------------------+
# | Generated by nginx-cert. Any manual change will be lost.                |
# |                                                                        |
# | To add your own configuration, drop a .conf file into                  |
# | /etc/nginx/conf.d/ (mounted from the host): it is included at the end  |
# | of the http block and may define its own servers.                      |
# |                                                                        |
# | To take full control: set CERT_MANAGE_NGINX=false and mount your own   |
# | /etc/nginx/nginx.conf. nginx-cert will keep managing certificates      |
# | without touching your configuration.                                   |
# +------------------------------------------------------------------------+

worker_processes      auto;
worker_rlimit_nofile  16384;
# In a directory owned by the runtime user: removing a file needs write
# permission on its directory, not on the file, so a pid directly under
# /var/run could be written but never unlinked at shutdown.
pid                   /var/run/nginx/nginx.pid;
error_log             /var/log/nginx/error.log notice;

events {
    worker_connections  %%WORKER_CONNECTIONS%%;
    multi_accept        on;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    charset       utf-8;

    # Do not disclose the nginx version in headers or error pages.
    server_tokens off;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" "$http_user_agent" '
                      'rt=$request_time uct=$upstream_connect_time urt=$upstream_response_time';

%%IF ACCESS_LOG%%
    access_log  /var/log/nginx/access.log  main;
%%ELSE%%
    access_log  off;
%%ENDIF%%

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    client_max_body_size    %%CLIENT_MAX_BODY_SIZE%%;
    client_body_timeout     30s;
    client_header_timeout   30s;
    send_timeout            30s;
    reset_timedout_connection on;

    gzip              on;
    gzip_vary         on;
    gzip_proxied      any;
    gzip_comp_level   5;
    gzip_min_length   256;
    gzip_types        text/plain text/css text/xml application/json application/javascript
                      application/xml application/xml+rss application/rss+xml
                      image/svg+xml font/woff font/woff2;

    # Required for OCSP stapling and for upstreams declared by name.
    # 127.0.0.11 is Docker's embedded DNS resolver.
    resolver          %%RESOLVER%% valid=300s ipv6=off;
    resolver_timeout  5s;

%%IF REAL_IP%%
    # Real client address when nginx sits behind a load balancer.
%%REAL_IP_DIRECTIVES%%
    real_ip_header    X-Forwarded-For;
    real_ip_recursive on;
%%ENDIF%%

    # http-level directives the generated servers rely on ($connection_upgrade).
    include /etc/nginx/snippets/nginx-cert-http.conf;

    # TLS policy shared by every server (see CERT_SSL_POLICY).
    include /etc/nginx/snippets/nginx-cert-tls.conf;

    # Servers generated by nginx-cert (nginx-cert.*.conf), then yours.
    include /etc/nginx/conf.d/*.conf;
}
