# Generated by nginx-cert for certificate "%%CERT_NAME%%".
#
# To replace this server with your own: drop your file into /etc/nginx/conf.d/
# and set CERT_MANAGE_VHOSTS=false. Certificates keep being managed and stay
# available at the paths below.

server {
    listen      %%HTTPS_PORT%% ssl%%DEFAULT_SUFFIX%%;
    listen      [::]:%%HTTPS_PORT%% ssl%%DEFAULT_SUFFIX%%;
%%IF HTTP3%%
    # HTTP/3 requires port %%HTTPS_PORT%% to be published over UDP as well.
    listen      %%HTTPS_PORT%% quic%%QUIC_EXTRA%%;
    listen      [::]:%%HTTPS_PORT%% quic%%QUIC_EXTRA%%;
%%ENDIF%%
    http2       %%HTTP2%%;
    server_name %%SERVER_NAMES%%;

    ssl_certificate           %%FULLCHAIN%%;
    ssl_certificate_key       %%PRIVKEY%%;
    # Trust chain used to verify the stapled OCSP response.
    ssl_trusted_certificate   %%CHAIN%%;
%%IF NO_STAPLING%%
    # Local certificate: it carries no OCSP responder URL, so stapling is
    # meaningless here (and nginx would warn on every start).
    ssl_stapling              off;
%%ENDIF%%

%%IF HSTS%%
    add_header Strict-Transport-Security "%%HSTS_VALUE%%" always;
%%ENDIF%%
    add_header X-Content-Type-Options    "nosniff" always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin" always;
    add_header X-Frame-Options           "SAMEORIGIN" always;
%%IF HTTP3%%
    add_header Alt-Svc                   'h3=":%%HTTPS_PORT%%"; ma=86400' always;
%%ENDIF%%

    # The challenge stays reachable over HTTPS: some authorities follow the
    # 308 redirect from port 80 before reading the token.
    location ^~ /.well-known/acme-challenge/ {
        root         %%WEBROOT%%;
        default_type "text/plain";
        try_files    $uri =404;
        access_log   off;
    }

%%IF HAS_UPSTREAM%%
    location / {
        # The upstream goes through a variable on purpose: with a hard-coded
        # name, nginx resolves it at configuration load time and refuses to
        # start until the application container exists -- which makes docker
        # compose start order critical. Through a variable, resolution happens
        # per request (see the resolver directive): the proxy always starts,
        # and returns 502 for as long as the upstream is missing.
        set $nc_upstream        "%%UPSTREAM_HOSTPORT%%";
        proxy_pass              %%UPSTREAM_SCHEME%%://$nc_upstream;
        proxy_http_version      1.1;
        proxy_set_header        Host              $host;
        proxy_set_header        X-Real-IP         $remote_addr;
        proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_set_header        X-Forwarded-Host  $host;
        proxy_set_header        X-Forwarded-Port  $server_port;
        # WebSocket relaying (see the $connection_upgrade map).
        proxy_set_header        Upgrade           $http_upgrade;
        proxy_set_header        Connection        $connection_upgrade;
        proxy_connect_timeout   %%PROXY_CONNECT_TIMEOUT%%;
        proxy_send_timeout      %%PROXY_TIMEOUT%%;
        proxy_read_timeout      %%PROXY_TIMEOUT%%;
        proxy_buffering         on;
    }
%%ELSE%%
    # No upstream declared (CERT_UPSTREAM, or "upstream=" in CERT_DOMAINS):
    # files under /var/www/html are served as-is.
    location / {
        root  /var/www/html;
        index index.html;
    }
%%ENDIF%%
}
