# Generated by nginx-cert -- shared TLS policy (CERT_SSL_POLICY=%%SSL_POLICY%%).
#
# "intermediate" follows Mozilla's recommendation of the same name: compatible
# with every reasonably up-to-date client, with no known compromise.
# "modern" allows TLS 1.3 only: maximum security, but cuts off clients older
# than roughly 2018.
#
# Finite-field ephemeral Diffie-Hellman suites (DHE-*) are deliberately absent:
# without ssl_dhparam nginx silently disables them anyway, and generating a DH
# group at startup would delay boot by several minutes. ECDHE suites cover the
# same needs with better performance.

%%IF MODERN%%
ssl_protocols              TLSv1.3;
%%ELSE%%
ssl_protocols              TLSv1.2 TLSv1.3;
ssl_ciphers                ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305;
%%ENDIF%%

# Since TLS 1.2 the recommendation is to let the client pick its cipher suite:
# it knows its own hardware acceleration better than the server does.
ssl_prefer_server_ciphers  off;

ssl_session_cache          shared:SSL:10m;
ssl_session_timeout        1d;
# Session tickets without key rotation break forward secrecy, and nginx cannot
# rotate them on its own.
ssl_session_tickets        off;

# OCSP stapling: saves the client a round-trip to the authority on every
# connection.
ssl_stapling               on;
ssl_stapling_verify        on;

# 0-RTT exposes non-idempotent requests to replay attacks.
ssl_early_data             off;
